# ingress:
#   enabled: true
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "nfs-client"
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: "Chnage45YourPass"
        username: "bn_keycloak"
        password: "Chnage4iTPass"
        database: "bitnami_keycloak"
  primary:
    persistence:
      size: 10Gi
  readReplicas:
    persistence:
      size: 10Gi
    replicaCount: 1
  architecture: replication
#End of DB Configuration
namespaceOverride: "keycloak-ns"
image:
  registry: docker.io
  repository: bitnami/keycloak
  tag: 24.0.4-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
auth:
  adminUser: admin
  adminPassword: "password4@Admin"
  existingSecret: ""
  passwordSecretKey: ""
  annotations: {}
service:
  type: ClusterIP
  http:
    enabled: true
  ports:
    http: 80
    https: 443