global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "nfs-client"
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: "ChnageYourPass"
        username: "bn_keycloak"
        password: "ChnagePass"
        database: "bitnami_keycloak"
  primary:
    persistence:
      size: 3000Mi
  readReplicas:
    persistence:
      size: 3000Mi
    replicaCount: 1
  architecture: replication
#End of DB Configuration
namespaceOverride: "keycloak"
image:
  registry: docker.io
  repository: bitnami/keycloak
  tag: 24.0.4-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false
auth:
  adminUser: admin
  adminPassword: "password"
  existingSecret: ""
  passwordSecretKey: ""
  annotations: {}
service:
  type: LoadBalancer
  http:
    enabled: true
  ports:
    http: 80
    https: 443